# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b840b1b027445573a748e176e06dcd991d9855b99cd9d3b76e867336860b8c6f0d48f4a97effe117d7b83a2672abfec8cbe05be821260c6faaad51a2f153e5e

test:
  secret_key_base: d07dc9043d0657befb097d7597bc8c1e0c127768b411f6694259b3144733b3dec3f70f6d72c5d6350f2e20974e9423e8d3ec8d9029dbcf40230ee965fb534e31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
